// Generated by tools/tool_contracts.py; do not edit manually.
using System;
using System.Collections.Generic;

namespace MCPForUnity.Editor.Services.Transport
{
    internal sealed class CommandRuntimeToolPolicy
    {
        internal CommandRuntimeToolPolicy(
            string name,
            string handler,
            bool requiresUnity,
            string mutationClass,
            bool destructive,
            bool triggersCompilation,
            bool requiresEditMode,
            bool undoable,
            bool supportsIfMatch)
        {
            Name = name;
            Handler = handler;
            RequiresUnity = requiresUnity;
            MutationClass = mutationClass;
            Destructive = destructive;
            TriggersCompilation = triggersCompilation;
            RequiresEditMode = requiresEditMode;
            Undoable = undoable;
            SupportsIfMatch = supportsIfMatch;
        }

        internal string Name { get; }
        internal string Handler { get; }
        internal bool RequiresUnity { get; }
        internal string MutationClass { get; }
        internal bool Destructive { get; }
        internal bool TriggersCompilation { get; }
        internal bool RequiresEditMode { get; }
        internal bool Undoable { get; }
        internal bool SupportsIfMatch { get; }
    }

    internal static class CommandRuntimeContract
    {
        internal const int ContractVersion = 1;
        internal const string BuiltInSchemaHash = "sha256:f52b331439fbc3a3deab7920e1f0788445cc905b1716cb29c453603627e9c679";

        internal static readonly IReadOnlyDictionary<string, CommandRuntimeToolPolicy>
            ToolPolicies = new Dictionary<string, CommandRuntimeToolPolicy>(StringComparer.Ordinal)
        {
            ["apply_text_edits"] = new CommandRuntimeToolPolicy("apply_text_edits", "manage_script", true, "asset", true, true, false, false, false),
            ["audit_project"] = new CommandRuntimeToolPolicy("audit_project", "audit_project", true, "read_only", false, false, false, false, false),
            ["batch_execute"] = new CommandRuntimeToolPolicy("batch_execute", "batch_execute", true, "external_side_effect", true, true, false, false, false),
            ["create_script"] = new CommandRuntimeToolPolicy("create_script", "manage_script", true, "asset", true, true, false, false, false),
            ["debug_request_context"] = new CommandRuntimeToolPolicy("debug_request_context", "debug_request_context", false, "read_only", false, false, false, false, false),
            ["delete_script"] = new CommandRuntimeToolPolicy("delete_script", "manage_script", true, "asset", true, true, false, false, false),
            ["execute_code"] = new CommandRuntimeToolPolicy("execute_code", "execute_code", true, "external_side_effect", true, true, false, false, false),
            ["execute_custom_tool"] = new CommandRuntimeToolPolicy("execute_custom_tool", "execute_custom_tool", true, "external_side_effect", true, false, false, false, false),
            ["execute_menu_item"] = new CommandRuntimeToolPolicy("execute_menu_item", "execute_menu_item", true, "external_side_effect", true, false, false, false, false),
            ["find_gameobjects"] = new CommandRuntimeToolPolicy("find_gameobjects", "find_gameobjects", true, "read_only", false, false, false, false, false),
            ["find_in_file"] = new CommandRuntimeToolPolicy("find_in_file", "manage_script", true, "read_only", false, false, false, false, false),
            ["generate_audio"] = new CommandRuntimeToolPolicy("generate_audio", "generate_audio", true, "external_side_effect", false, false, false, false, false),
            ["generate_image"] = new CommandRuntimeToolPolicy("generate_image", "generate_image", true, "external_side_effect", false, false, false, false, false),
            ["generate_model"] = new CommandRuntimeToolPolicy("generate_model", "generate_model", true, "external_side_effect", false, false, false, false, false),
            ["get_sha"] = new CommandRuntimeToolPolicy("get_sha", "manage_script", true, "read_only", false, false, false, false, false),
            ["get_test_job"] = new CommandRuntimeToolPolicy("get_test_job", "get_test_job", true, "read_only", false, false, false, false, false),
            ["import_model"] = new CommandRuntimeToolPolicy("import_model", "import_model", true, "asset", false, false, false, false, false),
            ["import_model_file"] = new CommandRuntimeToolPolicy("import_model_file", "import_model_file", true, "asset", false, false, false, false, false),
            ["inspect_dependencies"] = new CommandRuntimeToolPolicy("inspect_dependencies", "inspect_dependencies", true, "read_only", false, false, false, false, false),
            ["interact_play_mode"] = new CommandRuntimeToolPolicy("interact_play_mode", "interact_play_mode", true, "editor_state", true, false, false, false, false),
            ["manage_addressables"] = new CommandRuntimeToolPolicy("manage_addressables", "manage_addressables", true, "asset", true, false, true, false, false),
            ["manage_animation"] = new CommandRuntimeToolPolicy("manage_animation", "manage_animation", true, "asset", true, false, false, false, false),
            ["manage_asset"] = new CommandRuntimeToolPolicy("manage_asset", "manage_asset", true, "asset", true, true, false, false, false),
            ["manage_build"] = new CommandRuntimeToolPolicy("manage_build", "manage_build", true, "build", true, false, false, false, false),
            ["manage_camera"] = new CommandRuntimeToolPolicy("manage_camera", "manage_camera", true, "scene", true, false, false, true, false),
            ["manage_components"] = new CommandRuntimeToolPolicy("manage_components", "manage_components", true, "scene", true, false, false, true, false),
            ["manage_editor"] = new CommandRuntimeToolPolicy("manage_editor", "manage_editor", true, "project_settings", true, true, false, false, false),
            ["manage_gameobject"] = new CommandRuntimeToolPolicy("manage_gameobject", "manage_gameobject", true, "scene", true, false, false, true, true),
            ["manage_graphics"] = new CommandRuntimeToolPolicy("manage_graphics", "manage_graphics", true, "project_settings", true, false, false, false, false),
            ["manage_input"] = new CommandRuntimeToolPolicy("manage_input", "manage_input", true, "asset", true, true, true, false, false),
            ["manage_material"] = new CommandRuntimeToolPolicy("manage_material", "manage_material", true, "asset", true, false, false, false, false),
            ["manage_packages"] = new CommandRuntimeToolPolicy("manage_packages", "manage_packages", true, "package", true, true, false, false, false),
            ["manage_physics"] = new CommandRuntimeToolPolicy("manage_physics", "manage_physics", true, "scene", true, false, false, true, false),
            ["manage_prefabs"] = new CommandRuntimeToolPolicy("manage_prefabs", "manage_prefabs", true, "asset", true, false, false, false, false),
            ["manage_probuilder"] = new CommandRuntimeToolPolicy("manage_probuilder", "manage_probuilder", true, "scene", true, false, false, true, false),
            ["manage_profiler"] = new CommandRuntimeToolPolicy("manage_profiler", "manage_profiler", true, "editor_state", false, false, false, false, false),
            ["manage_scene"] = new CommandRuntimeToolPolicy("manage_scene", "manage_scene", true, "scene", true, false, false, true, false),
            ["manage_script"] = new CommandRuntimeToolPolicy("manage_script", "manage_script", true, "asset", true, true, false, false, false),
            ["manage_script_capabilities"] = new CommandRuntimeToolPolicy("manage_script_capabilities", "manage_script_capabilities", false, "read_only", false, false, false, false, false),
            ["manage_scriptable_object"] = new CommandRuntimeToolPolicy("manage_scriptable_object", "manage_scriptable_object", true, "asset", true, false, false, false, false),
            ["manage_shader"] = new CommandRuntimeToolPolicy("manage_shader", "manage_shader", true, "asset", true, false, false, false, false),
            ["manage_texture"] = new CommandRuntimeToolPolicy("manage_texture", "manage_texture", true, "asset", true, false, false, false, false),
            ["manage_tools"] = new CommandRuntimeToolPolicy("manage_tools", "manage_tools", false, "editor_state", false, false, false, false, false),
            ["manage_ui"] = new CommandRuntimeToolPolicy("manage_ui", "manage_ui", true, "asset", true, false, false, false, false),
            ["manage_vfx"] = new CommandRuntimeToolPolicy("manage_vfx", "manage_vfx", true, "asset", true, false, false, false, false),
            ["read_console"] = new CommandRuntimeToolPolicy("read_console", "read_console", true, "editor_state", true, false, false, false, false),
            ["refresh_unity"] = new CommandRuntimeToolPolicy("refresh_unity", "refresh_unity", true, "editor_state", true, true, false, false, false),
            ["run_tests"] = new CommandRuntimeToolPolicy("run_tests", "run_tests", true, "editor_state", true, false, false, false, false),
            ["script_apply_edits"] = new CommandRuntimeToolPolicy("script_apply_edits", "manage_script", true, "asset", true, true, false, false, false),
            ["set_active_instance"] = new CommandRuntimeToolPolicy("set_active_instance", "set_active_instance", true, "editor_state", false, false, false, false, false),
            ["unity_docs"] = new CommandRuntimeToolPolicy("unity_docs", "unity_docs", false, "read_only", false, false, false, false, false),
            ["unity_reflect"] = new CommandRuntimeToolPolicy("unity_reflect", "unity_reflect", true, "read_only", false, false, false, false, false),
            ["validate_script"] = new CommandRuntimeToolPolicy("validate_script", "manage_script", true, "read_only", false, false, false, false, false),
        };
    }
}
