#!/usr/bin/env python3
"""Validate, generate, install, and compare the canonical Unity MCP skill.

The repository root ``unity-mcp-skill`` directory is the only authored skill
source. ``Contracts/tool-contracts.v1.json`` is the normative built-in tool
contract. This utility keeps the generated contract index and installed client
copy tied to those sources without making the installed directory authoritative.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import sys
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
SKILL_ROOT = REPO_ROOT / "unity-mcp-skill"
SKILL_FILE = SKILL_ROOT / "SKILL.md"
CONTRACT_FILE = REPO_ROOT / "Contracts" / "tool-contracts.v1.json"
CONTRACT_INDEX = SKILL_ROOT / "references" / "tool-contract-index.md"
TOOLS_REFERENCE = SKILL_ROOT / "references" / "tools-reference.md"
CLAUDE_WRAPPER = REPO_ROOT / ".claude" / "skills" / "unity-mcp-skill" / "SKILL.md"
CLAUDE_WRAPPER_ROOT = CLAUDE_WRAPPER.parent
SYNC_SERVICE = (
    REPO_ROOT / "MCPForUnity" / "Editor" / "Setup" / "SkillSyncService.cs"
)
MANAGED_MARKER = ".unity-mcp-skill-sync"
CANONICAL_SKILL_NAME = "unity-mcp-orchestrator"


def _load_contract() -> dict[str, Any]:
    return json.loads(CONTRACT_FILE.read_text(encoding="utf-8"))


def _canonical_contract_hash(contract: dict[str, Any]) -> str:
    payload = json.dumps(
        contract,
        ensure_ascii=False,
        allow_nan=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    return "sha256:" + hashlib.sha256(payload).hexdigest()


def _escape_cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def _declared_actions(tool: dict[str, Any]) -> str:
    properties = tool.get("input_schema", {}).get("properties", {})
    action_schema = properties.get("action", {})
    actions = action_schema.get("enum")
    if not isinstance(actions, list) or not actions:
        return "-"
    return ", ".join(f"`{_escape_cell(action)}`" for action in actions)


def render_contract_index(contract: dict[str, Any]) -> str:
    tools = sorted(contract["tools"], key=lambda item: item["name"])
    lines = [
        "# Unity MCP Tool Contract Index",
        "",
        "> Generated by `tools/skill_contracts.py` from",
        "> `Contracts/tool-contracts.v1.json`. Do not edit this file manually.",
        "",
        f"Contract hash: `{_canonical_contract_hash(contract)}`",
        f"Built-in tools: `{len(tools)}`",
        "",
        "This is a static contract inventory, not a live availability report.",
        "Use the connected MCP tool list or `manage_tools(action=\"find\", ...)`",
        "to confirm what the current session exposes.",
        "",
        "| Tool | Group | Target | Mutation | Destructive | Retry | Unity | Declared actions |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for tool in tools:
        mutation = tool["mutation"]
        execution = tool["execution"]
        target = tool["execution_target"]
        availability = tool["availability"]
        lines.append(
            "| "
            + " | ".join(
                (
                    f"`{_escape_cell(tool['name'])}`",
                    (
                        "-"
                        if not tool.get("group")
                        else f"`{_escape_cell(tool['group'])}`"
                    ),
                    f"`{_escape_cell(target['kind'])}`",
                    f"`{_escape_cell(mutation['class'])}`",
                    "yes" if mutation["destructive"] else "no",
                    f"`{_escape_cell(execution['retry_semantics'])}`",
                    "yes" if availability["requires_unity"] else "no",
                    _declared_actions(tool),
                )
            )
            + " |"
        )
    return "\n".join(lines) + "\n"


def _git_blob_sha1(path: Path) -> str:
    content = path.read_bytes()
    header = f"blob {len(content)}\0".encode("utf-8")
    return hashlib.sha1(header + content).hexdigest()


def _skill_files(root: Path) -> dict[str, Path]:
    if not root.exists():
        return {}
    files: dict[str, Path] = {}
    for path in root.rglob("*"):
        if not path.is_file() or path.name == MANAGED_MARKER:
            continue
        if "__pycache__" in path.parts or path.suffix == ".pyc":
            continue
        files[path.relative_to(root).as_posix()] = path
    return files


def _source_revision(files: dict[str, Path]) -> str:
    canonical = "".join(
        f"{relative}\0{_git_blob_sha1(files[relative])}\n"
        for relative in sorted(files)
    ).encode("utf-8")
    return "sha256:" + hashlib.sha256(canonical).hexdigest()


def _frontmatter_fields(text: str) -> tuple[dict[str, str], list[str]]:
    errors: list[str] = []
    if not text.startswith("---\n"):
        return {}, ["SKILL.md must start with YAML frontmatter"]
    try:
        frontmatter, _ = text[4:].split("\n---\n", 1)
    except ValueError:
        return {}, ["SKILL.md frontmatter is not terminated"]
    fields: dict[str, str] = {}
    for line in frontmatter.splitlines():
        match = re.fullmatch(r"([A-Za-z][A-Za-z0-9_-]*):\s*(.*)", line)
        if not match:
            errors.append(f"unsupported frontmatter line: {line!r}")
            continue
        fields[match.group(1)] = match.group(2).strip()
    return fields, errors


def validate_repository() -> list[str]:
    errors: list[str] = []
    contract = _load_contract()
    skill_text = SKILL_FILE.read_text(encoding="utf-8")

    fields, frontmatter_errors = _frontmatter_fields(skill_text)
    errors.extend(frontmatter_errors)
    if set(fields) != {"name", "description"}:
        errors.append(
            "SKILL.md frontmatter must contain only name and description"
        )
    if fields.get("name") != CANONICAL_SKILL_NAME:
        errors.append(f"SKILL.md name must be {CANONICAL_SKILL_NAME!r}")
    description = fields.get("description", "")
    if not description or len(description) > 1024:
        errors.append("SKILL.md description must contain 1 to 1024 characters")
    if len(skill_text.splitlines()) >= 500:
        errors.append("SKILL.md must remain below 500 lines")

    linked_references = set(
        re.findall(r"\]\((references/[^)#]+)(?:#[^)]+)?\)", skill_text)
    )
    required_references = {
        "references/capabilities-and-limitations.md",
        "references/tool-contract-index.md",
        "references/tools-reference.md",
        "references/resources-reference.md",
        "references/workflows.md",
        "references/probuilder-guide.md",
    }
    missing_links = sorted(required_references - linked_references)
    if missing_links:
        errors.append(f"SKILL.md does not route to references: {missing_links}")
    for reference in sorted(linked_references):
        if not (SKILL_ROOT / reference).is_file():
            errors.append(f"SKILL.md links to missing file: {reference}")

    expected_index = render_contract_index(contract)
    actual_index = (
        CONTRACT_INDEX.read_text(encoding="utf-8")
        if CONTRACT_INDEX.exists()
        else None
    )
    if actual_index != expected_index:
        errors.append(
            "generated tool contract index is stale; run "
            "python tools/skill_contracts.py --update-index"
        )

    contract_names = {tool["name"] for tool in contract["tools"]}
    reference_text = TOOLS_REFERENCE.read_text(encoding="utf-8")
    documented_tools = set(
        re.findall(r"^###\s+([a-z][a-z0-9_]*)\s*$", reference_text, re.MULTILINE)
    )
    unknown_tools = sorted(documented_tools - contract_names)
    if unknown_tools:
        errors.append(
            f"tools-reference.md documents tools absent from the contract: {unknown_tools}"
        )

    interact = next(tool for tool in contract["tools"] if tool["name"] == "interact_play_mode")
    interact_actions = interact["input_schema"]["properties"]["action"]["enum"]
    missing_actions = [
        action for action in interact_actions if f"`{action}`" not in reference_text
    ]
    if missing_actions:
        errors.append(
            "interact_play_mode reference omits declared actions: "
            f"{missing_actions}"
        )

    wrapper_text = (
        CLAUDE_WRAPPER.read_text(encoding="utf-8")
        if CLAUDE_WRAPPER.exists()
        else ""
    )
    if "../../../unity-mcp-skill/SKILL.md" not in wrapper_text:
        errors.append("the .claude discovery skill does not route to the canonical skill")
    wrapper_duplicates = [
        path.relative_to(CLAUDE_WRAPPER_ROOT).as_posix()
        for path in CLAUDE_WRAPPER_ROOT.rglob("*")
        if path.is_file() and path != CLAUDE_WRAPPER
    ]
    if wrapper_duplicates:
        errors.append(
            "the .claude discovery skill contains duplicated files: "
            f"{sorted(wrapper_duplicates)}"
        )

    sync_text = SYNC_SERVICE.read_text(encoding="utf-8")
    if 'private const string SkillSubdir = "unity-mcp-skill";' not in sync_text:
        errors.append("SkillSyncService does not install from the canonical skill directory")

    return errors


def _default_codex_target() -> Path:
    codex_root = os.environ.get("CODEX_HOME")
    if codex_root:
        return Path(codex_root).expanduser() / "skills" / "unity-mcp-skill"
    return Path.home() / ".codex" / "skills" / "unity-mcp-skill"


def _validate_target(target: Path) -> Path:
    resolved = target.expanduser().resolve()
    if resolved.name != "unity-mcp-skill":
        raise RuntimeError(
            "refusing to manage a target not named 'unity-mcp-skill': "
            f"{resolved}"
        )
    if resolved == SKILL_ROOT.resolve():
        raise RuntimeError("canonical source and install target must be different")
    return resolved


def _can_adopt_legacy_target(target: Path, source_files: dict[str, Path]) -> bool:
    target_files = _skill_files(target)
    if not target_files:
        return True
    if "SKILL.md" not in target_files:
        return False
    source_top_levels = {name.split("/", 1)[0] for name in source_files}
    target_top_levels = {name.split("/", 1)[0] for name in target_files}
    return target_top_levels <= source_top_levels


def install_skill(target: Path) -> tuple[int, int, int, str]:
    target = _validate_target(target)
    source_files = _skill_files(SKILL_ROOT)
    if not source_files or "SKILL.md" not in source_files:
        raise RuntimeError(f"invalid canonical skill source: {SKILL_ROOT}")

    marker = target / MANAGED_MARKER
    if target.exists() and not marker.exists() and not _can_adopt_legacy_target(
        target, source_files
    ):
        raise RuntimeError(
            "refusing to overwrite an unmanaged install directory: " f"{target}"
        )

    target.mkdir(parents=True, exist_ok=True)
    installed_files = _skill_files(target)
    added = updated = deleted = 0

    for relative, source in sorted(source_files.items()):
        destination = target / Path(relative)
        if not destination.exists():
            added += 1
        elif destination.read_bytes() != source.read_bytes():
            updated += 1
        else:
            continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)

    for relative, destination in sorted(installed_files.items(), reverse=True):
        if relative in source_files:
            continue
        destination.unlink()
        deleted += 1

    for directory in sorted(
        (path for path in target.rglob("*") if path.is_dir()),
        key=lambda path: len(path.parts),
        reverse=True,
    ):
        if not any(directory.iterdir()):
            directory.rmdir()

    revision = _source_revision(source_files)
    marker.write_text(
        "managed-by-unity-mcp-skill-sync\n"
        f"source={SKILL_ROOT.resolve()}\n"
        "branch=local\n"
        f"revision={revision}\n"
        "subdir=unity-mcp-skill\n",
        encoding="utf-8",
        newline="\n",
    )
    return added, updated, deleted, revision


def compare_installed(target: Path) -> list[str]:
    target = _validate_target(target)
    errors: list[str] = []
    if not target.exists():
        return [f"installed skill directory does not exist: {target}"]

    source_files = _skill_files(SKILL_ROOT)
    installed_files = _skill_files(target)
    missing = sorted(set(source_files) - set(installed_files))
    extra = sorted(set(installed_files) - set(source_files))
    changed = sorted(
        relative
        for relative in set(source_files) & set(installed_files)
        if source_files[relative].read_bytes() != installed_files[relative].read_bytes()
    )
    if missing:
        errors.append(f"installed skill is missing files: {missing}")
    if extra:
        errors.append(f"installed skill has extra files: {extra}")
    if changed:
        errors.append(f"installed skill has changed files: {changed}")

    marker = target / MANAGED_MARKER
    if not marker.exists():
        errors.append("installed skill has no ownership/provenance marker")
    else:
        marker_text = marker.read_text(encoding="utf-8-sig")
        expected_revision = f"revision={_source_revision(source_files)}"
        if expected_revision not in marker_text.splitlines():
            errors.append("installed skill provenance revision is stale")
    return errors


def _print_errors(title: str, errors: list[str]) -> None:
    print(title, file=sys.stderr)
    for error in errors:
        print(f"  - {error}", file=sys.stderr)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--update-index",
        action="store_true",
        help="regenerate references/tool-contract-index.md from the contract",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate canonical skill, generated index, wrapper, and installer routing",
    )
    parser.add_argument(
        "--install",
        action="store_true",
        help="mirror the canonical skill into the managed Codex skill directory",
    )
    parser.add_argument(
        "--check-installed",
        action="store_true",
        help="compare the managed Codex installation with the canonical source",
    )
    parser.add_argument(
        "--target",
        type=Path,
        default=None,
        help="override the installed skill directory",
    )
    args = parser.parse_args(argv)

    if not any((args.update_index, args.check, args.install, args.check_installed)):
        args.check = True

    if args.update_index:
        content = render_contract_index(_load_contract())
        CONTRACT_INDEX.parent.mkdir(parents=True, exist_ok=True)
        CONTRACT_INDEX.write_text(content, encoding="utf-8", newline="\n")
        print(f"Updated {CONTRACT_INDEX.relative_to(REPO_ROOT)}")

    repository_errors = validate_repository()
    if repository_errors:
        _print_errors("Canonical skill validation failed:", repository_errors)
        return 1
    if args.check or args.update_index:
        tools = len(_load_contract()["tools"])
        print(f"Canonical skill validation passed ({tools} built-in tools).")

    target = args.target or _default_codex_target()
    if args.install:
        try:
            added, updated, deleted, revision = install_skill(target)
        except RuntimeError as exc:
            _print_errors("Skill installation failed:", [str(exc)])
            return 1
        print(
            "Installed canonical skill "
            f"(+{added} ~{updated} -{deleted}, {revision}) at "
            f"{_validate_target(target)}"
        )

    if args.check_installed or args.install:
        try:
            installed_errors = compare_installed(target)
        except RuntimeError as exc:
            installed_errors = [str(exc)]
        if installed_errors:
            _print_errors("Installed skill validation failed:", installed_errors)
            return 1
        print(f"Installed skill matches canonical source at {_validate_target(target)}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
